spring:
  application:
    name: leave-service
  datasource:
    url: jdbc:postgresql://localhost:5434/leave_db
    username: hrms_user
    password: hrms_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jackson:
    mapper:
      accept-case-insensitive-enums: true

server:
  port: 8083

service:
  employee-service:
    url: http://localhost:8081

feign:
  client:
    config:
      default:
        loggerLevel: basic
