spring:
  application:
    name: auth-service
    server:
      port: 8084
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
