version: '3.8'

services:
  postgres-employee-service:
    image: postgres:15-alpine
    container_name: hr-postgres-employee
    environment:
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_password
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - employee_pgdata:/var/lib/postgresql/data

  postgres-payroll-service:
    image: postgres:15-alpine
    container_name: hr-postgres-payroll
    environment:
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_password
      POSTGRES_DB: payroll_db
    ports:
      - "5433:5432"
    volumes:
      - payroll_pgdata:/var/lib/postgresql/data

  postgres-leave-service:
    image: postgres:15-alpine
    container_name: hr-postgres-leave
    environment:
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_password
      POSTGRES_DB: leave_db
    ports:
      - "5434:5432"
    volumes:
      - leave_pgdata:/var/lib/postgresql/data

volumes:
  employee_pgdata:
  payroll_pgdata:
  leave_pgdata:
